version: '3.0'

services:
            
  discoveryservice:
    image: aista/discovery-service
    container_name: discoveryservice
    ports:
      - '8761:8080'
    environment:
      - 'eviction-interval-timer-in-ms: 1000'
